version: "3.9"

services:
  ratings:
    build: .
    image: registry.demo.opsta.co.th/training[X]/bookinfo/ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:5.0.8-debian-10-r12
    volumes:
      - "./databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_EXTRA_USERNAMES: ratings
      MONGODB_EXTRA_PASSWORDS: CHANGEME
      MONGODB_EXTRA_DATABASES: ratings